baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "https://twitter.com/bahaistudies"
  github: "https://github.com/bahaistudies"
  linkedin: "https://www.linkedin.com/company/bahaistudies"
  vimeo: "https://vimeo.com/bahaistudies"
  instagram: "https://instagram.com/bahaistudies"
  facebook: "https://facebook.com/bahaistudies"
taxonomies:
  author: authors
